language: java
jdk:
- oraclejdk8
addons:
  ssh_known_hosts:
  - 159.65.124.37
env:
  global:
  - REMOTE_USER=deploy
  - REMOTE_HOST=159.65.124.37
  - REMOTE_APP_DIR=/home/deploy
before_install:
- openssl aes-256-cbc -K $encrypted_33d270911dca_key -iv $encrypted_33d270911dca_iv
  -in deploy.enc -out deploy -d
- chmod +x mvnw
- chmod +x ./scripts/deploy.sh
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
- "./mvnw clean package"
after_success:
- "./scripts/deploy.sh"
